USE [master]
GO

/****** Object:  Database [BDmed]    Script Date: 29.01.2021 21:41:58 ******/
CREATE DATABASE [BDmed]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDmed', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BDmed.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDmed_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BDmed_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDmed].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDmed] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDmed] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDmed] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDmed] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDmed] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDmed] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDmed] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDmed] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDmed] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDmed] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDmed] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDmed] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDmed] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDmed] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDmed] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDmed] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDmed] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDmed] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDmed] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDmed] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDmed] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDmed] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDmed] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDmed] SET  MULTI_USER 
GO

ALTER DATABASE [BDmed] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDmed] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDmed] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDmed] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDmed] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDmed] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDmed] SET  READ_WRITE 
GO

